config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'fwp#index'

  resources :fwp do
    collection do 
      get "one"
      get "two"
      get "three"
      get "four"
      get "five"
    end
  end

  resources :cases do
    member do
      get :get_json
    end
  end

  resources :case_results
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/case.rb
class Case < ApplicationRecord
  has_many :case_results
  
  scope :find_name, -> (name) { where("name like ?", "%#{name}%") if name.present? }
  scope :find_username, -> (username) { where("username like ?", "%#{username}%") if username.present? }
  scope :find_tag, -> (tag) { where("tag like ?", "%#{tag}%") if tag.present? }
end

app/models/case_result.rb
require 'csv'

class CaseResult < ApplicationRecord
  serialize :result_array, Array
  serialize :path_array, Array

  belongs_to :case

  scope :find_case_name, -> (case_name) { where("case_name like ?", "%#{case_name}%") if case_name.present? }
  scope :find_case_type, -> (case_type) { where(case_type: case_type) if case_type.present? }
  
  def case_type_view
    case case_type
    when "S"
      "低强度地震"
    when "M1"
      "中等强度地震"
    when "L"
      "高强度地震"
    end
  end
  
  def self.to_csv
    attributes = %w{case_name case_tag case_desc case_type_view result_text path_text}

    CSV.generate(headers: true) do |csv|
      csv << %w{编号 案例名称 案例关键词 案例描述 地震强度 灾害后果 灾害演化路径}

      find_each.with_index do |cr, index|
        csv << attributes.map{ |attr| cr.send(attr) }.unshift(index + 1)
      end
    end.encode('gb2312', :invalid => :replace, :undef => :replace, :replace => "?")
  end

  def result_text
    result_array.join("\r\n")
  end

  def path_text
    path_array.join("\r\n")
  end

  def case_desc
    self.case&.desc
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/case_results_controller.rb
class CaseResultsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:create]

  def index
    case_results = CaseResult.find_case_name(params[:case_name])
                              .find_case_type(params[:case_type])
    if params[:format] == "csv"
      respond_to do |format|
        format.html
        format.csv { send_data case_results.to_csv, filename: "result-#{Time.current.strftime("%Y%m%d%H%M%S")}.csv" }
      end
    else
      @case_results = case_results.page(params[:page]).per(8)
    end
  end

  def create
    @case_result = CaseResult.new(case_result_params)
    @case_result.case_name = @case_result.case.name
    @case_result.case_tag = @case_result.case.tag
    if @case_result.save
			render json: { status: 'ok', message: '保存成功' }
		else
			render json: { status: 'error', message: '保存失败' }
		end
  end

  def export
    @case_result = CaseResult.find(params[:id])
    respond_to do |format|
      format.html
      format.csv { send_data @case_result.to_csv, filename: "#{@case_result.case_name}-#{@case_result.case_type_view}.csv" }
    end
  end

  def destroy
    @case_result = CaseResult.find(params[:id])
    @case_result.delete
    flash[:success] = "删除成功"
    redirect_to case_results_url
  end

  private

    def case_result_params
      params.require(:case_result).permit(:case_id, :case_type, result_array: [], path_array: [])
    end
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:get_json]

  def index
    @cases = Case.find_name(params[:name])
                 .find_username(params[:username])
                 .find_tag(params[:tag])
                 .page(params[:page])
                 .per(8)
  end

  def new
    @case = Case.new
  end

  def create
    @case = Case.new(case_params)
    @case.file = params[:case][:file].original_filename
    @case.file_body = File.read(params[:case][:file].tempfile)
    if @case.save
			flash[:success] = "案例添加成功"
			redirect_to root_url
		else
			flash.now[:error] = "案例添加失败。#{@case.errors.full_messages.to_sentence}"
			render :new
		end
  end

  def show
    @case = Case.find_by(id: params[:id])
  end

  def destroy
    @case = Case.find_by(id: params[:id])
    if @case && @case.delete 
      flash[:success] = "案例删除成功"
    else
      flash[:error] = "案例删除失败。"
    end
    redirect_to cases_url
  end

  def get_json
    @case = Case.find_by(id: params[:id])
    render json: { status: 'ok', data: JSON.parse(@case.file_body) }
  end

  def get_current_path
    
  end

  private

    def case_params
      params.require(:case).permit(:username, :name, :tag, :desc, :time)
    end
end

app/controllers/fwp_controller.rb
class FwpController < ApplicationController
  def index
    
  end

  def one
    
  end

  def two
    
  end

  def three
    
  end

  def four
    
  end

  def five
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
   def flash_class(level)
    case level
      when "notice" then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-danger"
      when "alert" then "alert alert-danger"
    end
  end
end

app/views/case_results/index.html.erb
<div class="row" style="margin-top: 20px;">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          结果导出
        </h3>
      </div>
      <div class="panel-body">
        <%= form_tag({ controller: 'case_results', action: :index }, method: :get) do %>
          <div class="row">
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="name" class="control-label">案例名称</label>
                  <%= text_field_tag :case_name, params[:case_name], class: "form-control", placeholder: "请输入案例名称" %>
                </div>
              </div>
              <div class="col-sm-6">
                <div class="form-group">
                  <label for="name" class="control-label">地震强度</label>
                  <%= select_tag(:case_type, options_for_select([['低强度地震', "S"], ['中等强度地震', "M1"], ["高强度地震", "L"]], params[:case_type]), include_blank: true, class: 'form-control') %>
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-sm-4">
              <div class="form-group">
                  <input type="submit" class="btn btn-primary" name="commit" value="查询" data-disable-with="查询中。。。">
                  <%= link_to "导出", case_results_path(format: "csv"), class: "btn btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>
        <br>
        <hr style="display: block;height: 1px;border: 0;border-top: 1px dashed #ccc;margin: 1em 0;padding: 0; ">
        <div class="row">
          <div class="col-lg-12">
            <table class="table table-striped table-bordered table-hover dataTables-example">
              <thead>
                <tr>
                    <th>ID</th>
                    <th>案例名称</th>
                    <th>案例关键词</th>
                    <th>地震强度</th>
                    <th style="width: 18%;">灾害后果</th>
                    <th style="width: 50%;">灾害演化路径</th>
                    <th>操作</th>
                </tr>
              </thead>
            <tbody>
              <% @case_results.each do |item| %>
                <tr>
                  <td><%= item.id %></td>
                  <td><%= item.case_name %></td>
                  <td><%= item.case_tag %></td>
                  <td><%= item.case_type_view %></td>
                  <td><%= item.result_array.join('<br>').html_safe %></td>
                  <td><%= item.path_array.join('<br>').html_safe %></td>
                  <td><%= link_to '删除', item, method: :delete, data: { confirm: '确定删除?' }, class: "btn btn-primary btn-block" %></td>
                </tr>
              <% end %>
            </tbody>
            <%# <tfoot>
              <tr>
                  <th>案例ID</th>
                  <th>案例名称</th>
                  <th>用户名称</th>
                  <th>关键词</th>
                  <th>案例描述</th>
                  <th>案例数据</th>
                  <th>操作</th>
              </tr>
            </tfoot> %>
          </table>
          <%= paginate @case_results %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cases/index.html.erb
<div class="row" style="margin-top: 20px;">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          案例检索
        </h3>
      </div>
      <div class="panel-body">
        <%= form_tag({ controller: 'cases', action: :index }, method: :get) do %>
          <div class="row">
              <div class="col-sm-4">
                <div class="form-group">
                  <label for="name" class="control-label">案例名称</label>
                  <%= text_field_tag :name, params[:name], class: "form-control", placeholder: "请输入商品名称" %>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                  <label for="name" class="control-label">用户名称</label>
                  <%= text_field_tag :username, params[:username], class: "form-control", placeholder: "请输入商品名称" %>
                </div>
              </div>
              <div class="col-sm-4">
                <div class="form-group">
                  <label for="name" class="control-label">案例关键词</label>
                  <%= text_field_tag :tag, params[:tag], class: "form-control", placeholder: "请输入商品名称" %>
                </div>
              </div>
          </div>
          <div class="row">
            <div class="col-sm-4">
              <div class="form-group">
                  <input type="submit" class="btn btn-primary" name="commit" value="查询" data-disable-with="查询中。。。">
              </div>
            </div>
          </div>
        <% end %>
        <br>
        <hr style="display: block;height: 1px;border: 0;border-top: 1px dashed #ccc;margin: 1em 0;padding: 0; ">
        <div class="row">
          <div class="col-lg-12">
            <table class="table table-striped table-bordered table-hover dataTables-example">
              <thead>
                <tr>
                    <th>案例ID</th>
                    <th>案例名称</th>
                    <th>用户名称</th>
                    <th>关键词</th>
                    <th style="width:30%;">案例描述</th>
                    <th>案例数据</th>
                    <th>操作</th>
                </tr>
              </thead>
            <tbody>
              <% @cases.each do |item| %>
                <tr>
                  <td><%= item.id %></td>
                  <td><%= item.name %></td>
                  <td><%= item.username %></td>
                  <td><%= item.tag %></td>
                  <td><%= item.desc %></td>
                  <td><%= item.file %></td>
                  <td><%= link_to '删除', item, method: :delete, data: { confirm: '确定删除?' }, class: "btn btn-danger" %></td>
                </tr>
              <% end %>
            </tbody>
            <%# <tfoot>
              <tr>
                  <th>案例ID</th>
                  <th>案例名称</th>
                  <th>用户名称</th>
                  <th>关键词</th>
                  <th>案例描述</th>
                  <th>案例数据</th>
                  <th>操作</th>
              </tr>
            </tfoot> %>
          </table>
          <%= paginate @cases %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cases/new.html.erb
<div class="row" style="margin-top: 20px;">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          管廊事故灾害案例输入
        </h3>
      </div>
      <div class="panel-body">
        <%= form_for @case, :html => { :onsubmit => "return submitForm();" }, class: "form-horizontal" do |f| %>
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <div class="col-sm-6 formGroup1" style="line-height: 34px;">
                <label>案例名称</label>
                <%= f.text_field :name, class: "form-control", placeholder: '请输入案例名称' %>
                <span class="help-block helpBlock1" style="display: none;">请先输入案例名称</span>
              </div>
              <div class="col-sm-6 formGroup2" style="line-height: 34px;">
                <label>发生时间</label>
                <%= f.text_field :time, class: "form-control", placeholder: '请输入发生时间(2019/01/01 00:00:00)' %>
                <span class="help-block helpBlock2" style="display: none;">请先输入发生时间</span>
              </div>
              <div class="col-sm-6 formGroup3" style="line-height: 34px;">
                <label>用户名称</label>
                <%= f.text_field :username, class: "form-control", placeholder: '请输入用户名称' %>
                <span class="help-block helpBlock3" style="display: none;">请先输入用户名称</span>
              </div>
              <div class="col-sm-6 formGroup4" style="line-height: 34px;">
                <label>案例关键词</label>
                <%= f.text_field :tag, class: "form-control", placeholder: '请输入案例关键词' %>
                <span class="help-block helpBlock4" style="display: none;">请先输入案例关键词</span>
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <div class="col-sm-12 formGroup5" style="line-height: 34px;">
                <label>案例描述</label>
                <%= f.text_area :desc, class: "form-control", placeholder: '请输入案例描述' %>
                <span class="help-block helpBlock5" style="display: none;">请先输入案例描述</span>
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <div class="col-sm-12 formGroup6" style="line-height: 34px;">
                <label>添加数据</label>
                <%= f.file_field :file, class: "form-control" %>
                <span class="help-block helpBlock6" style="display: none;">请先上传数据文件</span>
              </div>
            </div>
          </div>
          <br>
          <div class="row">
            <div class="col-sm-10 col-sm-offset-1">
              <div class="col-sm-12" style="line-height: 34px;">
                <button type="submit" class="btn btn-default">确定</button>
              </div>
            </div>
          </div>  
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
    function submitForm() {
      if ($('#case_name').val() === "") {
        $('.formGroup1').addClass('has-error')
        $('.helpBlock1').show()
        setTimeout(function () {
          $('.formGroup1').removeClass('has-error')
          $('.helpBlock1').hide()
        }, 3000)
      }
      if ($('#case_time').val() === "") {
        $('.formGroup2').addClass('has-error')
        $('.helpBlock2').show()
        setTimeout(function () {
          $('.formGroup2').removeClass('has-error')
          $('.helpBlock2').hide()
        }, 3000)
      }
      if ($('#case_username').val() === "") {
        $('.formGroup3').addClass('has-error')
        $('.helpBlock3').show()
        setTimeout(function () {
          $('.formGroup3').removeClass('has-error')
          $('.helpBlock3').hide()
        }, 3000)
      }
      if ($('#case_tag').val() === "") {
        $('.formGroup4').addClass('has-error')
        $('.helpBlock4').show()
        setTimeout(function () {
          $('.formGroup4').removeClass('has-error')
          $('.helpBlock4').hide()
        }, 3000)
      }
      if ($('#case_desc').val() === "") {
        $('.formGroup5').addClass('has-error')
        $('.helpBlock5').show()
        setTimeout(function () {
          $('.formGroup5').removeClass('has-error')
          $('.helpBlock5').hide()
        }, 3000)
      }
      if ($('#case_file').val() === "") {
        $('.formGroup6').addClass('has-error')
        $('.helpBlock6').show()
        setTimeout(function () {
          $('.formGroup6').removeClass('has-error')
          $('.helpBlock6').hide()
        }, 3000)
      }
      if ($('#case_name').val() === "" ||  $('#case_time').val() === "" || $('#case_username').val() === "" || $('#case_tag').val() === "" || $('#case_desc').val() === "" || $('#case_file').val() === "") {
        return false
      }
    }
</script>

app/views/fwp/five.html.erb
<div class="row" style="margin-top: 20px;">
  <div class="col-sm-10 col-sm-offset-1">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">
          联系我们
        </h3>
      </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <div class="row">
              <div style="text-align: center;">
                <h4>联系方式</h4>
                <p>我们的电子邮箱随时准备着接收来自您的消息:</p>
                <em>164861381@qq.com</em> 
              </div>
              <%# <div class="col-sm-6" style="text-align: center;">
                <h4>服务热线</h4>
                <p>我们的服务热线会随时为您解答任何疑问:</p>
                <em>164861381@qq.com</em> 
              </div> %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/fwp/four.html.erb
<div class="row" style="margin-top: 20px;">
</div>

app/views/fwp/index.html.erb
<div class="backImg" style="height: 100vh;">
  <div class="row">
    <div class="col-sm-8 col-sm-offset-2 indexTitle">
      <span>城市综合管廊耦合事故灾害演化仿真模拟软件</span>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="img" style="float: left;width: 60%;height: 540px;margin-top: 20px;margin-left:5%">
        <img src="http://nhsoft-pintuan.oss-cn-shanghai.aliyuncs.com/public/system/mercury/asset2s/attachments/000/001/506/original/indexLeft.jpeg" alt="", style="width: 100%;height:100%;">
      </div>
      <div class="backImg2" style="float: left;width: 25%;height: 540px;margin-top: -5px;margin-left:5%;margin-right:5%;">
        <a href="<%= new_case_path %>" class="block2">
          <span>管廊事故灾害案例输入</span>
        </a>
        <a href="<%= three_fwp_index_path %>" class="block2">
          <span>管廊事故灾害模拟仿真</span>
        </a>
        <a href="<%= case_results_path %>" class="block2">
          <span>结果导出</span>
        </a>
      </div>
    </div>
  </div>
</div>

app/views/fwp/one.html.erb
<div class="row" style="margin-top: 20px;">
</div>

app/views/fwp/two.html.erb
<div class="row" style="margin-top: 20px;">
</div>

app/views/layouts/_flash_message.html.erb
<div id="flash">
  <% flash.each do |key, value| %>
    <div class="flash-hide <%= flash_class(key) %>" role="alert" style="position: fixed;z-index: 100000000; width: 400px; margin-left: auto;margin-right: auto;left:0px; right:0px;">
      <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
      <strong><%= value %></strong>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation" style="margin-bottom: 0;">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%= root_path %>" style="font-size: 22px;font-weight: bold;">城市综合管廊耦合事故灾害演化仿真模拟软件</a>
    </div>
    <div>
      <ul class="nav navbar-nav" style="float: right;">
        <li><a href="<%= five_fwp_index_path %>">联系我们</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evolution-Utility tunnel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/flash_message' %>
    <%= render 'layouts/navigation' %>
    <%= yield %>
  </body>
</html>